version: '3.8'

services:
  # PHP + Apache Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deviceshop
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=deviceshop
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db
    networks:
      - my-network

  # MySQL Service
  db:
    image: mysql:8.0.35
    container_name: dbdeviceshop
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: deviceshop
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - my-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
      - my-network

volumes:
  dbdata:

networks:
  my-network:
    driver: bridge
